//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace taulty { namespace lightbulb {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IlightbulbService. Instead, lightbulbServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class lightbulbServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IlightbulbService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<lightbulbServiceEventAdapter^, lightbulbSwitchCalledEventArgs^>^ SwitchCalled;
    event Windows::Foundation::TypedEventHandler<lightbulbServiceEventAdapter^, lightbulbGetLocationCalledEventArgs^>^ GetLocationCalled;
    event Windows::Foundation::TypedEventHandler<lightbulbServiceEventAdapter^, lightbulbGetStatusCalledEventArgs^>^ GetStatusCalled;

    // Property Read Events
    
    // Property Write Events

    // IlightbulbService Implementation
    virtual Windows::Foundation::IAsyncOperation<lightbulbSwitchResult^>^ SwitchAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ bool interfaceMemberOn);
    virtual Windows::Foundation::IAsyncOperation<lightbulbGetLocationResult^>^ GetLocationAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<lightbulbGetStatusResult^>^ GetStatusAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);


};

} } } 
