//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace taulty { namespace lightbulb {

ref class lightbulbConsumer;

public ref class lightbulbSwitchResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static lightbulbSwitchResult^ CreateSuccessResult()
    {
        auto result = ref new lightbulbSwitchResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static lightbulbSwitchResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new lightbulbSwitchResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class lightbulbGetLocationResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Platform::String^ Returnvalue
    {
        Platform::String^ get() { return m_interfaceMemberReturnvalue; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberReturnvalue = value; }
    }
    
    static lightbulbGetLocationResult^ CreateSuccessResult(_In_ Platform::String^ interfaceMemberReturnvalue)
    {
        auto result = ref new lightbulbGetLocationResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Returnvalue = interfaceMemberReturnvalue;
        return result;
    }
    
    static lightbulbGetLocationResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new lightbulbGetLocationResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    Platform::String^ m_interfaceMemberReturnvalue;
};

public ref class lightbulbGetStatusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool Returnvalue
    {
        bool get() { return m_interfaceMemberReturnvalue; }
    internal:
        void set(_In_ bool value) { m_interfaceMemberReturnvalue = value; }
    }
    
    static lightbulbGetStatusResult^ CreateSuccessResult(_In_ bool interfaceMemberReturnvalue)
    {
        auto result = ref new lightbulbGetStatusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Returnvalue = interfaceMemberReturnvalue;
        return result;
    }
    
    static lightbulbGetStatusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new lightbulbGetStatusResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    bool m_interfaceMemberReturnvalue;
};

public ref class lightbulbJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property lightbulbConsumer^ Consumer
    {
        lightbulbConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ lightbulbConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    lightbulbConsumer^ m_consumer;
};

} } } 
